In [1]:
import pandas as pd
import numpy as np
clicks_dtypes = {'advertiser': np.int8, 'action_id': np.float16, 'source_id': np.int8, 'country_code': 'category',
                 'latitude': np.float16, 'longitude': np.float16, 'carrier_id': np.float16, 'brand': np.float16,
                 'touchX': np.float16, 'touchY': np.float16}
clicks = pd.read_csv('clicks.csv.gzip', dtype = clicks_dtypes, compression = 'gzip')

In [2]:
clicks.head(3)

,advertiser_id,action_id,source_id,created,country_code,latitude,longitude,wifi_connection,carrier_id,trans_id,os_minor,agent_device,os_major,specs_brand,brand,timeToClick,touchX,touchY,ref_type,ref_hash
0,2,NaN,4,2019-03-06T22:42:12.755Z,6333597102633388268,1.206055,1.070312,False,1.0,iGgClCM9exiHF4K31g94XmvHEBSLKIY,6.768137e+18,NaN,3.072849e+18,2733035977666442898,NaN,1.563,0.904785,0.078003,1891515180541284343,1904083516767779093
1,0,NaN,0,2019-03-08T10:24:30.641Z,6333597102633388268,1.218750,1.071289,False,4.0,MMHTOJ6qKAOeIH_Eywh1KIcCaxtO9oM,3.025219e+18,NaN,1.774085e+18,392184377613098015,NaN,NaN,NaN,NaN,1891515180541284343,3086509764961796666
2,0,NaN,0,2019-03-08T15:24:16.069Z,6333597102633388268,1.206055,1.070312,False,6.0,vIrEIdf9izUaWdAri6Ezk7T3nHFvNQU,5.975656e+18,NaN,3.072849e+18,392184377613098015,NaN,NaN,0.945801,0.472900,1891515180541284343,6958163894863846647

In [3]:
clicks.drop('action_id', axis = 1, inplace = True)

In [4]:
clicks.head(3)

,advertiser_id,source_id,created,country_code,latitude,longitude,wifi_connection,carrier_id,trans_id,os_minor,agent_device,os_major,specs_brand,brand,timeToClick,touchX,touchY,ref_type,ref_hash
0,2,4,2019-03-06T22:42:12.755Z,6333597102633388268,1.206055,1.070312,False,1.0,iGgClCM9exiHF4K31g94XmvHEBSLKIY,6.768137e+18,NaN,3.072849e+18,2733035977666442898,NaN,1.563,0.904785,0.078003,1891515180541284343,1904083516767779093
1,0,0,2019-03-08T10:24:30.641Z,6333597102633388268,1.218750,1.071289,False,4.0,MMHTOJ6qKAOeIH_Eywh1KIcCaxtO9oM,3.025219e+18,NaN,1.774085e+18,392184377613098015,NaN,NaN,NaN,NaN,1891515180541284343,3086509764961796666
2,0,0,2019-03-08T15:24:16.069Z,6333597102633388268,1.206055,1.070312,False,6.0,vIrEIdf9izUaWdAri6Ezk7T3nHFvNQU,5.975656e+18,NaN,3.072849e+18,392184377613098015,NaN,NaN,0.945801,0.472900,1891515180541284343,6958163894863846647

In [5]:
clicks['wifi_connection'].value_counts()

False    26351
Name: wifi_connection, dtype: int64

In [6]:
clicks.drop('wifi_connection', axis = 1, inplace = True)

In [7]:
clicks.head(3)

,advertiser_id,source_id,created,country_code,latitude,longitude,carrier_id,trans_id,os_minor,agent_device,os_major,specs_brand,brand,timeToClick,touchX,touchY,ref_type,ref_hash
0,2,4,2019-03-06T22:42:12.755Z,6333597102633388268,1.206055,1.070312,1.0,iGgClCM9exiHF4K31g94XmvHEBSLKIY,6.768137e+18,NaN,3.072849e+18,2733035977666442898,NaN,1.563,0.904785,0.078003,1891515180541284343,1904083516767779093
1,0,0,2019-03-08T10:24:30.641Z,6333597102633388268,1.218750,1.071289,4.0,MMHTOJ6qKAOeIH_Eywh1KIcCaxtO9oM,3.025219e+18,NaN,1.774085e+18,392184377613098015,NaN,NaN,NaN,NaN,1891515180541284343,3086509764961796666
2,0,0,2019-03-08T15:24:16.069Z,6333597102633388268,1.206055,1.070312,6.0,vIrEIdf9izUaWdAri6Ezk7T3nHFvNQU,5.975656e+18,NaN,3.072849e+18,392184377613098015,NaN,NaN,0.945801,0.472900,1891515180541284343,6958163894863846647

In [8]:
clicks['agent_device'].value_counts()

3.516812e+18    656
1.754528e+18    326
6.882415e+18    156
7.787531e+18    132
4.281729e+18    122
4.445252e+18     99
6.589622e+18     87
2.066431e+17     81
3.686067e+17     75
8.656854e+18     74
5.990117e+18     72
7.116343e+18     70
1.063783e+18     68
2.616228e+18     64
8.163783e+18     62
8.604122e+18     47
3.977966e+18     46
2.438316e+18     43
4.430579e+18     33
1.181318e+18     32
5.960896e+18     28
1.540907e+18     28
8.535198e+18     23
3.432684e+18     23
3.051485e+18     22
1.321681e+18     22
2.293453e+18     21
1.966828e+18     20
6.558466e+18     20
7.628197e+18     19
               ...
8.178177e+18      1
8.285870e+18      1
8.400757e+18      1
7.052220e+18      1
6.445596e+18      1
3.103697e+17      1
1.251416e+17      1
4.928434e+18      1
1.231797e+18      1
3.262918e+18      1
4.186571e+18      1
3.339732e+17      1
6.195314e+18      1
7.614489e+18      1
3.285184e+18      1
2.091433e+17      1
8.369550e+18      1
1.557569e+18      1
4.497716e+18      1
4.155763e+18      1
1.623311e+18      1
2.863247e+18      1
1.198454e+18      1
7.407931e+18      1
5.399765e+16      1
2.108514e+17      1
8.214238e+18      1
4.125471e+18      1
3.889747e+18      1
1.595841e+18      1
Name: agent_device, Length: 190, dtype: int64

In [9]:
clicks['brand'].value_counts()

2.0     2027
0.0     1917
1.0     1521
4.0      240
3.0      186
5.0      129
6.0      124
7.0       32
9.0       31
8.0       16
10.0       8
12.0       3
13.0       1
Name: brand, dtype: int64

In [10]:
clicks["created"] =  pd.to_datetime(clicks["created"], errors = "coerce")

In [12]:
clicks.dtypes

advertiser_id             int64
source_id                  int8
created          datetime64[ns]
country_code           category
latitude                float16
longitude               float16
carrier_id              float16
trans_id                 object
os_minor                float64
agent_device            float64
os_major                float64
specs_brand               int64
brand                   float16
timeToClick             float64
touchX                  float16
touchY                  float16
ref_type                  int64
ref_hash                  int64
dtype: object

In [13]:
clicks.head()

,advertiser_id,source_id,created,country_code,latitude,longitude,carrier_id,trans_id,os_minor,agent_device,os_major,specs_brand,brand,timeToClick,touchX,touchY,ref_type,ref_hash
0,2,4,2019-03-06 22:42:12.755,6333597102633388268,1.206055,1.070312,1.0,iGgClCM9exiHF4K31g94XmvHEBSLKIY,6.768137e+18,NaN,3.072849e+18,2733035977666442898,NaN,1.563,0.904785,0.078003,1891515180541284343,1904083516767779093
1,0,0,2019-03-08 10:24:30.641,6333597102633388268,1.218750,1.071289,4.0,MMHTOJ6qKAOeIH_Eywh1KIcCaxtO9oM,3.025219e+18,NaN,1.774085e+18,392184377613098015,NaN,NaN,NaN,NaN,1891515180541284343,3086509764961796666
2,0,0,2019-03-08 15:24:16.069,6333597102633388268,1.206055,1.070312,6.0,vIrEIdf9izUaWdAri6Ezk7T3nHFvNQU,5.975656e+18,NaN,3.072849e+18,392184377613098015,NaN,NaN,0.945801,0.472900,1891515180541284343,6958163894863846647
3,2,3,2019-03-06 03:08:51.543,6333597102633388268,1.206055,1.070312,45.0,YaKxxEAs2UmZhSpRfiCO9Zpa82B_AKM,6.768137e+18,NaN,3.072849e+18,2733035977666442898,NaN,19.013,0.035004,0.430908,1891515180541284343,4368617728156436525
4,2,3,2019-03-06 03:32:55.570,6333597102633388268,1.206055,1.070312,45.0,X5XTOcYQovkl6yadYdAD7xioVGU9jiY,6.768137e+18,NaN,3.072849e+18,2733035977666442898,NaN,28.110,0.053986,0.423096,1891515180541284343,4368617728156436525